### ISSUE TITLE
Error on Injection in UWP

### ISSUE THREAD

**Issue by agreed31579** [IShade4ReaI/NetflixCE#4]
Error:...etflixCE-main\netflix\netflix\netflix\autorun\roblox.lua:347: bad argument #2 to 'format' (number expected, got nil)
stack traceback:
	[C]: in function 'string.format'
	...etflixCE-main\netflix\netflix\netflix\autorun\roblox.lua:347: in function <...etflixCE-main\netflix\netflix\netflix\autorun\roblox.lua:93>

**Comment by agreed31579** [comment]
Nvm I fixed it on UWP

**Comment by SoftwarePixel** [comment]
You should close the issue if you've got it working.
