### ISSUE TITLE
Error Injecting (attempt to compare two nil values)

### ISSUE THREAD

**Issue by SoftwarePixel** [IShade4ReaI/NetflixCE#6]
Hello, I've installed all the redistributables, and added any missing dll files and every game I try to inject, I get this error:

Got result: 2A412A0CAA8 
Got result: 2A43C6474D8 
Players: 2A43C647490 
Name offset: 48 
Parent offset: 60 
DataModel: 2A436DD87A0 
Children offset: 50 
Players->LocalPlayer offset: 230 
Got localplayer: 2A436DD7C60 
Got localplayer: trauredenkp 
Got backpack: 2A4425EB3E0 
Got tool:  Normal Punch 
Error:...nloads\NetflixCE-main\netflix\netflix\autorun\roblox.lua:214: attempt to compare two nil values
stack traceback:
	...nloads\NetflixCE-main\netflix\netflix\autorun\roblox.lua:214: in method 'getChildren'
	...nloads\NetflixCE-main\netflix\netflix\autorun\roblox.lua:233: in method 'findFirstClass'
	...nloads\NetflixCE-main\netflix\netflix\autorun\roblox.lua:311: in function <...nloads\NetflixCE-main\netflix\netflix\autorun\roblox.lua:93>

**Comment by SoftwarePixel** [comment]
Never mind, I got it working. By the way, I really appreciate you guys making this public to all of us. You really didn't need to make it open sourced and provide all this documentation, but it's really appreciated. Thank you so much for this!

**Comment by robloxxxerr2** [comment]
> Never mind, I got it working. By the way, I really appreciate you guys making this public to all of us. You really didn't need to make it open sourced and provide all this documentation, but it's really appreciated. Thank you so much for this!

How did you fix it? i have the same issue.

**Comment by SoftwarePixel** [comment]
Not exactly sure to be honest. I restarted my PC and after playing around with it a bit I got it to work, I still get the error sometimes but if you play around with it enough it seems to work.


Also, for the developers, please open source the baseplate rbxl file so we can host the game ourselvs when roblox eventually takes it down. Please also add a jobID value for more advanced users so we can specify what server we want to go into. Here's an example from the docs (https://create.roblox.com/docs/reference/engine/classes/TeleportService#TeleportToPlaceInstance):

local TeleportService = game:GetService("TeleportService")
local Players = game:GetService("Players")

Players.PlayerAdded:Connect(function(player)
	-- Is this player following anyone?
	local followId = player.FollowUserId
	-- If so, find out where they are
	if followId and followId ~= 0 then
		local _currentInstance, placeId, jobId
		local success, errorMessage, _currentInstance, placeId, jobId = pcall(function()
			-- followId is the user ID of the player that you want to retrieve the place and job ID for
			return TeleportService:GetPlayerPlaceInstanceAsync(followId)
		end)
		if success then
			-- Teleport player
			TeleportService:TeleportToPlaceInstance(placeId, jobId, player)
		else
			warn(errorMessage)
		end
	else
		warn("Player " .. player.UserId .. " is not following another player!")
	end
end)

**Comment by SoftwarePixel** [comment]
You don't need to worry about all the following stuff. Just see how they included a job ID argument to the TeleportToPlaceInstance function.

**Comment by robloxxxerr2** [comment]
Alr thx bro
