### ISSUE TITLE
Error, wont work on web vers or UWP vers

### ISSUE THREAD

**Issue by SoulessShxdow** [IShade4ReaI/NetflixCE#8]
Got result: 195AD1C9728 
Got result: 195B41407B8 
Players: 195B4140770 
Name offset: 48 
Parent offset: 60 
DataModel: 195DA9C5BA0 
Children offset: 50 
Players->LocalPlayer offset: 240 
Got localplayer: 195DA9C6460 
Got localplayer: r_psong 
Got backpack: 19608F4FAA0 
Got tool:  Cell Phone 
Got tool script:  Cell Phone LS 
Error:...etflixCE-main\netflix\netflix\netflix\autorun\roblox.lua:347: bad argument #2 to 'format' (number expected, got nil)
stack traceback:
	[C]: in function 'string.format'
	...etflixCE-main\netflix\netflix\netflix\autorun\roblox.lua:347: in function <...etflixCE-main\netflix\netflix\netflix\autorun\roblox.lua:93>

**Comment by SoulessShxdow** [comment]
and laggy asf

**Comment by SoulessShxdow** [comment]
FIXED

**Comment by SoulessShxdow** [comment]
wait is freezing

**Comment by jrigle** [comment]
how did you fix it?

**Comment by wwewew2** [comment]
same issue, how did you fix it??
